sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
  - '4'
  - '0.12'
  - '0.10'
# Chrome browser fix
# https://github.com/MrOrz/SeeSS/blob/master/.travis.yml
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
#
script: node_modules/karma/bin/karma start test/karma.conf.js --single-run
before_install:
  - npm i -g npm@^2.0.0
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
